# Generated by Django 5.0.3 on 2024-03-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('num_images', models.IntegerField(blank=True, null=True)),
                ('cover_ext', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
