# Generated by Django 5.0.3 on 2024-03-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres', '0002_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
