# Generated by Django 5.0.3 on 2024-03-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres', '0003_alter_book_table_alter_image_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_ext',
            new_name='coverExt',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='num_images',
            new_name='numImages',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='additional_context',
            new_name='additionalContext',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='after_context',
            new_name='afterContext',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='before_context',
            new_name='beforeContext',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='gen_alt',
            new_name='genAlt',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='gen_image_caption',
            new_name='genImageCaption',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='original_alt',
            new_name='originalAlt',
        ),
    ]
