# Generated by Django 5.0.3 on 2024-03-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres', '0004_rename_cover_ext_book_coverext_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
    ]
